version: "3"
services:
  mongo:
    container_name: metis-mongo
    image: "mongo:3.6"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
      - 28017:28017
    command: --quiet
  redis:
    container_name: metis-redis
    image: "redis"
    ports:
      - "6379:6379"
  metis:
    container_name: metis-app
    build: .
    image: metis:1.0
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"
      - "4001:4001"
    restart: always
    command: npm run ${NODE_RUN_SCRIPT}
    volumes:
      - ./:/apps/metis
      - /apps/metis/node_modules
